on:
  push:
    branches:
      - main

jobs:
  install_dependency_job:
    name: build blog 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.14.0
      - uses: actions/setup-node@v3
        with:
          node-version: 14.17.6
          cache:
            "pnpm"
            # cache: "npm"
      - name: "show nodejs version"
        run: node -v
      - name: install dependency
        run: pnpm install --no-frozen-lockfile
        # run: npm i
      - name: run build
        run: npm run build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with: 
          name: dist
          path: ./dist
      # - name: ftp-action
      #   uses: sebastianpopp/ftp-action@v2.0.0
      #   with:
      #     host: ${{secrets.HOST}}
      #     user: ${{secrets.USER}}
      #     password: ${{secrets.PASSWORD}}
      #     localDir: "dist"
      #     remoteDir: "react-blog"
  build-docker-image:
    name: build docker image
    # 获取install_dependency_job 缓存的工件
    needs: install_dependency_job
    runs-on: ubuntu-latest
    steps:
        
      # docker相关操作
      # 注意 先checkout 再download 上一个job upload artifact
      # checkout 将当前git项目作为当前工作目录
      - name: Checkout
        uses: actions/checkout@v3
      - name: download dist
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: ./dist
      - name: Display structure of downloaded files
        run: ls -R
      - name: show pwd
        run: pwd
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2
      # 有bug
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: 528491526/blog:latest
      # 登录部署服务器 拉取镜像并运行
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          # username: ${{ secrets.SSH_USERNAME }}
          # password: ${{ secrets.SSH_PASSWORD }}
          username: ${{ secrets.SSH_EMAIL }}
          key: ${{secrets.SSH_KEY}}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker pull 528491526/blog
            docker run --name blog -p 8084:8080 -d blog
      # - name: executing remote ssh commands using password
      #   uses: garygrossgarten/github-action-ssh@release
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.SSH_USERNAME }}
      #     passphrase: ${{ secrets.SSH_PASSWORD }}
      #     port : ${{ secrets.SSH_PORT}}
      #     command: |
      #       docker pull 528491526/blog
      #       docker run --name blog -p 8084:80 -d 528491526/blog
